spring:
  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12A808?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S09P12A808@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: qGTLED3jP0
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 7